### ISSUE TITLE
Conflict of the latest version with minecraft 1.19.2

### ISSUE THREAD

**Issue by ghost** [BumbleSoftware/Fastload#105]
### What went wrong?

Version incompatibility error

### Reproduction steps

I ran on version 1.19.2 with sodium,lithium and irlis

### Crash Report & Log

I cut a little because there is a report on the rest of the mods that just run

[14:31:13] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!

	 - Mod 'Fastload Fabric-api Forwarding' (fastload_fapi_forward) 1.0.2 requires version 1.20 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]

### Fastload Config

Not generated

### Environment

Fastload 3.4.0, Fabric 0.14.14, 1.19.2

**Comment by MrBOOMberMAN** [comment]
same here

**Comment by Soriiaano07** [comment]
i got this and there are no higher versions of fabric than 0.14.21
![image](https://github.com/BumbleSoftware/Fastload/assets/138610340/fff520c2-a600-41b4-b0a3-ebc7db935a26)

**Comment by ghost** [comment]
There was an error in the text:

1 - bootloader version was 0.14.21

2 - an error pops up with any lack of dependencies, without errors it just loads minecraft

**Comment by Soriiaano07** [comment]
how do i fix it

**Comment by ghost** [comment]
I think so too
