### ISSUE TITLE
Game crash on world load with MidnightControls

### ISSUE THREAD

**Issue by tzmanish** [BumbleSoftware/Fastload#13]
## Description
Game crashes on world load with [MidnightControls](https://github.com/TeamMidnightDust/MidnightControls) mod installed besides Fastload, Works fine if I disable either of them.

## Context
- OS: Windows 10
- Minecraft 1.18.2
- Fabric 1.14.8
- Mods: Fastload 1.1.2+1.18.2, MidnightControls 1.0.0+1.18
- Branch: Release

## NotEnoughCrashes log:
```
---- Minecraft Crash Report ----
// You're mean.

Time: 27/06/22, 12:57 am
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_1755" because "this.client" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at eu.midnightdust.midnightcontrols.client.gui.MidnightControlsHud.render(MidnightControlsHud.java:81)
	at dev.lambdaurora.spruceui.hud.HudManager.lambda$initialize$0(HudManager.java:38)
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.lambda$forEach$0(Object2ObjectMap.java:212)
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapEntrySet.fastForEach(Object2ObjectOpenHashMap.java:1051)
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.forEach(Object2ObjectMap.java:215)
	at dev.lambdaurora.spruceui.hud.HudManager.lambda$initialize$1(HudManager.java:36)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.client.gui.hud.InGameHud.handler$bnl000$render(InGameHud:4029)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:415)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:858)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eu.midnightdust.midnightcontrols.client.gui.MidnightControlsHud.render(MidnightControlsHud.java:81)
	at dev.lambdaurora.spruceui.hud.HudManager.lambda$initialize$0(HudManager.java:38)
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.lambda$forEach$0(Object2ObjectMap.java:212)
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapEntrySet.fastForEach(Object2ObjectOpenHashMap.java:1051)
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.forEach(Object2ObjectMap.java:215)
	at dev.lambdaurora.spruceui.hud.HudManager.lambda$initialize$1(HudManager.java:36)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$bnl000$render(class_329.java:4029)
	at net.minecraft.class_329.method_1753(class_329.java:415)

-- Affected level --
Details:
	All players: 1 total; [class_746['tz'/103, l='ClientLevel', x=445.57, y=82.00, z=289.66]]
	Chunk stats: 1024, 538
	Level dimension: minecraft:overworld
	Level spawn location: World: (432,75,240), Section: (at 0,11,0 in 27,4,15; chunk contains blocks 432,-64,240 to 447,319,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5430 game time, 5430 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 338165088 bytes (322 MiB) / 1001390080 bytes (955 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.21
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c20
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1640
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e9b
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8681
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 18658.30
	Virtual memory used (MB): 7033.84
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 39.48
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
			cloth-config: Cloth Config v6 6.0.42
				cloth-basic-math: cloth-basic-math 0.6.0
		alternate-current: Alternate Current 1.3.0
		betterfpsdist: Better FPS distance Mod 1.18-1.8
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.7.0
			com_ishland_c2me_libs_: libs 0.2.0+alpha.7.0
		carpet: Carpet Mod 1.4.69
		carpet-extra: Carpet Extra 1.4.72
		debugify: Debugify 1.11.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enhancedblockentities: Enhanced Block Entities 0.6+1.18.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		entityculling: EntityCulling-Fabric 1.5.1
		fabric: Fabric API 0.56.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.0+6f01bfd860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.13+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.0+e747827960
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.0+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.3+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.2+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.1+e747827960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.0+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.17.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fastload: Fast Load 1.1.2+1.18.2
		ferritecore: FerriteCore 4.2.1
		indium: Indium 1.0.3+mc1.18.2
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		java: Java HotSpot(TM) 64-Bit Server VM 17
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.10
		malilib: MaLiLib 0.12.1
		memoryleakfix: memory Leak Fix 1.18.2-0.3.5
		midnightcontrols: MidnightControls 1.0.0+1.18
			midnightlib: MidnightLib 0.4.0
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
			spruceui: SpruceUI 3.3.2+1.17
		midnightcontrols-extra: MidnightControls Extra 1.0.0
		minecraft: Minecraft 1.18.2
		minihud: MiniHUD 0.22.0
		modmenu: Mod Menu 3.2.2
		moreculling: More Culling 1.18.2-0.1.4-alpha
		nofade: No Fade 1.18-2.0.1
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		recipecache: recipecache 0.2.1-1.17.1
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.18.2-build.42
		smoothboot: Smooth Boot 1.18.2-1.7.0
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.5+mc1.18.2-build.42
			caffeineconfig: CaffeineConfig 1.1.0
		starlight: Starlight 1.0.2+fabric.89b8d9f
		zoomify: Zoomify 1.6.0
			dev_isxander_settxi: settxi 2.1.1
			settxicloth: Settxi Cloth Impl 1.0.2
	Loaded Shaderpack: (off)
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 630 GL version 3.2.0 - Build 27.20.100.8681, Intel
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['tz'/103, l='ServerLevel[New World]', x=445.57, y=82.00, z=289.66]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Rendering (v1) (fabric-rendering-v1), MidnightControls (midnightcontrols), SpruceUI (spruceui)
```

**Comment by StockiesLad** [comment]
It works fine on 1.19 for me. Can you try to reproduce this on 1.19? It isn't because I want to only support the latest version, it is because I have seen some 1.19 exclusive updates for MidnightControls. This means that the latest updates need to be backported to 1.18.2 to fix this. If, indeed 1.19 has no issues.

If 1.19 works: {
- Submit an issue to their Github, stating the same things.
- Try to get Motschen to backport the newer features to 1.18.2 to resolve this.
}
Else: {
I'll continue to diagnose the issues if 1.19 still has issues on your end.
}

**Comment by StockiesLad** [comment]
Also, I see that you have debugify, that mod implements a worse iteration of Force Close Loading Screen. I'd recommend you switch it off in the configs to disable the feature on its end. My implementation is safer, and faster. No offence to the author of Debugify.

**Comment by samos667** [comment]
> Also, I see that you have debugify, that mod implements a worse iteration of Force Close Loading Screen. I'd recommend you switch it off in the configs to disable the feature on its end. My implementation is safer, and faster. No offence to the author of Debugify.

Damn i have this issue on loading world. My CPU reach 100% and game not responding. Luckily this ticket exists thanks. U think is possible to add this on curseforge page with the specific MC-xxxxx to disable ? Is this that ? 
![image](https://user-images.githubusercontent.com/50653464/206346522-c5ce4dc7-51d9-4be4-bd18-5ef9e0e012d4.png)

**Comment by StockiesLad** [comment]
This is weird, debugify should be disabling this automatically. are you using the latest version?

**Comment by StockiesLad** [comment]
You should open a ticket to debugify, since this is something that isXander needs to disable
