### ISSUE TITLE
Client classes are loaded on the server

### ISSUE THREAD

**Issue by Lemmmy** [BumbleSoftware/Fastload#40]
Since v2.6.0 (specifically commit e6977e5ff40d1d4af8a38563641a11b99daa5074), the mod initialises FLClientHandler in `onInitialize()`, which leads to trying to load client-side classes on the server, and subsequently a crash on startup. The issue is still present on v2.6.5, Fabric 1.19.3

Code: https://github.com/BumbleSoftware/Fastload/blob/b8eb035ef55e0b93c8ae415fd910d1783beb83b1/src/main/java/io/github/bumblesoftware/fastload/init/FastLoad.java#L29-L33

Blame: https://github.com/BumbleSoftware/Fastload/blame/b8eb035ef55e0b93c8ae415fd910d1783beb83b1/src/main/java/io/github/bumblesoftware/fastload/init/FastLoad.java#L31

Stack trace:

```
[23:39:36] [main/ERROR] (net.minecraft.server.Main) Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fastload'!
        at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.11.jar:?]
        at net.minecraft.server.Main.main(Main:102) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.19.3-loader.0.14.11-launcher.0.11.1.jar:0.11.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
        at io.github.bumblesoftware.fastload.init.FastLoad.onInitialize(FastLoad.java:31) ~[Fastload+1.19.3-2.6.5.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at io.github.bumblesoftware.fastload.init.FastLoad.onInitialize(FastLoad.java:31) ~[Fastload+1.19.3-2.6.5.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
        ... 8 more
```

**Comment by StockiesLad** [comment]
Ahh i see, I'll fix this

**Comment by StockiesLad** [comment]
Should be fixed now. Reopen if you still have issues.

**Comment by Lemmmy** [comment]
Thanks for the quick fix!!

**Comment by StockiesLad** [comment]
np
