### ISSUE TITLE
Non-Blocking VersionChecker error on forge server 1.19.2

### ISSUE THREAD

**Issue by simcolin** [BumbleSoftware/Fastload#49]
Logs :
```
[08:48:10] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [fastload] Starting version check at https://github.com/BumbleSoftware/Fastload/raw/mc1.19.2/dev/updates.json
[08:48:11] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%2370!/:?] {}
        at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[fmlcore-1.19.2-43.2.3.jar%23258!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) [?:?] {re:mixin}
        at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.19.2-43.2.3.jar%23258!/:?] {}
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2370!/:?] {}
        ... 6 more
```

The url meant to be fetched is most likely : https://raw.githubusercontent.com/BumbleSoftware/Fastload/Forge-1.19.2/updates.json

**Comment by StockiesLad** [comment]
Sorry for the wait. Basically, all the devs are busy rn (plus I don't work on forge). Although, you might be able to get this resolved quicker if you joined in the discord and talked the AbdElAziz (The forge lead).
