### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SpiritOTHawk** [BumbleSoftware/Fastload#59]
```
---- Minecraft Crash Report ----
// My bad.
Time: 2023-04-04 18:34:33
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fastload'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.class_6489.getName()'
	at io.github.bumblesoftware.fastload.util.MinecraftVersionUtil.compareAll(MinecraftVersionUtil.java:10)
	at io.github.bumblesoftware.fastload.init.FastloadClient.handler$bjn000$fl-119-0-1-2-compat$compat119(FastloadClient.java:520)
	at io.github.bumblesoftware.fastload.init.FastloadClient.getAbstractedClient(FastloadClient.java)
	at io.github.bumblesoftware.fastload.init.FastloadClient.<clinit>(FastloadClient.java:12)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
Mixins in Stacktrace:
	net.minecraft.class_310:
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		me.axieum.mcmod.authme.mixin.MinecraftClientAccessor (authme.mixins.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (citresewn-defaults.mixins.json)
		io.github.thecsdev.tcdcommons.client.mixin.events.MixinMinecraftClient (tcdcommons.client.mixin.events.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (fallingleaves.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		me.jellysquid.mods.sodium.mixin.workarounds.issue1486.MixinMinecraftClient (sodium.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		club.chachy.lazylanguageloader.client.mixin.optimizations.splash.MixinMinecraftClient (lazy-language-loader.mixin.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		com.tterrag.blur.mixin.MixinMinecraftClient (mixins.blur.json)
		com.aizistral.nochatreports.common.mixins.client.MixinMinecraft (mixins/common/nochatreports.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
		squeek.appleskin.mixin.MinecraftClientMixin (appleskin.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		io.grayray75.fabric.fpsdisplay.mixin.MinecraftClientMixin (fpsdisplay.mixins.json)
		com.ishland.vmp.mixins.timesource.MixinMinecraftClient (vmp.mixins.json)
		dev.isxander.debugify.client.mixins.basic.mc46766.MinecraftMixin (debugify.client.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		io.wispforest.owo.mixin.MinecraftClientMixin (owo.mixins.json)
		io.wispforest.owo.mixin.ui.MinecraftClientMixin (owo.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		com.aizistral.nochatreports.fabric.mixins.client.MixinMinecraft (mixins/fabric/nochatreports-fabric.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		io.github.bumblesoftware.fastload.mixin.mixins.client.MinecraftClientMixin (fastload.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (sodium.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		link.infra.screenshotclipboard.common.mixin.AWTHackMixin (screenshotclipboard-common.mixins.json)
		io.github.ultimateboomer.smoothboot.mixin.client.MainMixin (smoothboot.mixins.json)
-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Linux (amd64) version 6.1.22-1-lts
	Java Version: 17.0.6, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 815256224 bytes (777 MiB) / 1073741824 bytes (1024 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: HD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x591b
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7944.86
	Virtual memory used (MB): 4094.17
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 21 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=30 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=200 -XX:G1HeapRegionSize=8M -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:+UseDynamicNumberOfGCThreads -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+UseInterpreter -XX:+RewriteFrequentPairs -Xms1024m -Xmx4096m
	Fabric Mods: 
		appleskin: AppleSkin 2.4.3+mc1.19.4
		authme: Auth Me 6.0.0
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		betterst
ats: Better Statistics Screen 2.5.2+1.19.4
			tcdcommons: TCD Commons API 2.5.1+1.19.4
				architectury: Architectury 8.1.73
		blur: Blur (Fabric) 3.0.0
			midnightlib: MidnightLib 1.2.1
			satin: Satin 1.11.0
		borderlessmining: Borderless Mining 1.1.7+1.19.4
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.42
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.42
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.42
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.42
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.42
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.42
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.42
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.42
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.42
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.42
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.42
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.42
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.42
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.42
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.42
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.42
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.42
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.42
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.42
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.42
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cherishedworlds: Cherished Worlds 6.0.4+1.19.4
		citresewn: CIT Resewn 1.1.3+1.19.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.4
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 10.0.0.2
		craftpresence: CraftPresence 2.0.0-beta.3
		cull-less-leaves: Cull Less Leaves 1.1.0
			com_github_llamalad7_mixinextras: mixinextras 0.1.1
		customsplashscreen: Custom Splash Screen 1.2.0
		debugify: Debugify 1.19.4+1.0
		detailab: Detail Armor Bar 2.6.3+1.19.4-fabric
		eatinganimationid: Eating Animation 1.9.3
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		fabric-api: Fabric API 0.77.0+1.19.4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.25+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.4+ae0966baf4
			fabric-commands-v0: Fabric Commands (v0) 0.2.42+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.53+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.7+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.6+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.3+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b3f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.25+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.29+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.37+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.0+a6f3ccfaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.40+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.1+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.7+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.3+a383ab97f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.4+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.0+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.37+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.40+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.0+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.44+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.19+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.0.1+9003cbe9f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabricloader: Fabric Loader 0.14.19
		fallingleaves: Falling Leaves 1.15.0+1.19.4
		fastload: Fast Load 3.0.1
			conditional-mixin: conditional mixin 0.3.2
			fl-119-0-1-2-compat: Fastload 1.19-0-1-2 Compat 3.0.1
			fl-1193-compat: Fastload 1.19.3 Compat 3.0.1
			fl-1194-compat: Fastload 1.19.4 Compat 3.0.1
		ferritecore: FerriteCore 5.2.0
		fpsdisplay: FPS-Display 1.5.0+1.19
		immediatelyfast: ImmediatelyFast 1.1.11
			net_lenni0451_reflect: Reflect 1.1.0
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		isxander-main-menu-credits: Main Menu Credits 1.1.1
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.2
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazy-language-loader: lazy-language-loader 0.3.2
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.1
		minecraft: Minecraft 1.19.4
		mixintrace: MixinTrace 1.1.1+1.17
		moderate-loading-screen: Mod-erate Loading Screen 1.2.1+1.19.4
			cicada: CICADA 0.1.2
				langfiles-plus: Langfiles Plus 1.0.0
		modmenu: Mod Menu 6.1.0-rc.4
			fabric-api-base: Fabric API Base 0.4.23+9ff28bcef4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.0+938a1d56f4
		mousetweaks: Mouse Tweaks 2.24
		nochatreports: No Chat Reports 1.19.4-v2.1.1
		owo: oωo 0.10.3+1.19.4
			blue_endless_jankson: jankson 1.2.2
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		shulkerboxtooltip: Shulker Box Tooltip 3.2.5+1.19.4
		skinlayers: 3d Skin Layers 1.5.3-mc1.19.4
		smoothboot: Smooth Boot 1.19.4-1.7.0
		smoothswapping: Smooth Swapping 0.8
		sodium: Sodium 0.4.10+build.24
		sspb: Sodium Shadowy Path Blocks 3.1.0
		starlight: Starlight 1.1.1+fabric.ae22326
		visuality: Visuality 0.7.0
		vmp: Very Many Players 0.2.0+beta.7.69
		waterdripsound: Drip Sounds 1.19-0.3.2
		yet-another-config-lib: YetAnotherConfigLib 2.4.0
	Launched Version: 1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by StockiesLad** [comment]
This is an already known bug, pleasae read the changelog
