### ISSUE TITLE
Server error with version 3.3.8

### ISSUE THREAD

**Issue by sternschnaube** [BumbleSoftware/Fastload#86]
I upgraded from version 3.3.7 to 3.3.8 and run into this error.
I removed the old config but the bug still occur.
Client loads Fastload fine and it's marked as 1.19.4 compatible, the version I am using.
Fabric API 0.79.0 and Loader 0.14.19.

Failed to parse variable 'chunk_try_limit' in Fastload's config, generating a new one!
[19:11:24] [Server thread/WARN]: Failed to parse variable 'debug' in Fastload's config, generating a new one!
[19:11:24] [Server thread/WARN]: Failed to parse variable 'instant_load' in Fastload's config, generating a new one!
[19:11:24] [Server thread/WARN]: Failed to parse variable 'local_render_chunk_radius' in Fastload's config, generating a new one!
[19:11:24] [Server thread/WARN]: Failed to parse variable 'server_render_chunk_radius' in Fastload's config, generating a new one!
[19:11:24] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/class_437
	at io.github.bumblesoftware.fastload.init.FastloadClient.md1539cd$fastload-1194-compat$lambda$register1194$0$5(FastloadClient.java:1526) ~[Fastload+1.18.2-1.20-3.3.8.jar:?]
	at io.github.bumblesoftware.fastload.api.events.AbstractEvent$StableEventArgs.recursive(AbstractEvent.java:219) ~[Fastload+1.18.2-1.20-3.3.8.jar:?]
	at io.github.bumblesoftware.fastload.api.events.CapableEvent.lambda$fireEvent$2(CapableEvent.java:175) ~[Fastload+1.18.2-1.20-3.3.8.jar:?]
	at io.github.bumblesoftware.fastload.api.events.CapableEvent.iterate(CapableEvent.java:164) ~[Fastload+1.18.2-1.20-3.3.8.jar:?]
	at io.github.bumblesoftware.fastload.api.events.CapableEvent.fireEvent(CapableEvent.java:175) ~[Fastload+1.18.2-1.20-3.3.8.jar:?]
	at io.github.bumblesoftware.fastload.api.events.AbstractEvent.fireEvent(AbstractEvent.java:162) ~[Fastload+1.18.2-1.20-3.3.8.jar:?]
	at io.github.bumblesoftware.fastload.init.FastloadClient.getAbstractedClient(FastloadClient.java:50) ~[Fastload+1.18.2-1.20-3.3.8.jar:?]
	at io.github.bumblesoftware.fastload.init.FastloadClient.<clinit>(FastloadClient.java:29) ~[Fastload+1.18.2-1.20-3.3.8.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96) ~[fabric-loader-0.14.19.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at ca.fxco.memoryleakfix.fabric.MemoryLeakFixFabric.internalForceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFixFabric.java:40) ~[memoryleakfix-fabric-1.17+-1.0.0.jar:?]
	at ca.fxco.memoryleakfix.fabric.MemoryLeakFixFabric.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFixFabric.java:32) ~[memoryleakfix-fabric-1.17+-1.0.0.jar:?]
	at net.minecraft.server.MinecraftServer.handler$eai000$memoryleakfix$memoryLeakFix$loadAllMixinsServerSide(MinecraftServer.java:14321) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:340) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:169) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 22 more
[19:11:25] [Server thread/ERROR]: This crash report has been saved to: /mnt/minecraft/./crash-reports/crash-2023-04-24_19.11.25-server.txt
[19:11:25] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "me.glitch.aitecraft.shareenderchest.SharedInventory.getList(net.minecraft.class_2371)" because "me.glitch.aitecraft.shareenderchest.ShareEnderChest.sharedInventory" is null
	at me.glitch.aitecraft.shareenderchest.ShareEnderChest.saveInventory(ShareEnderChest.java:77) ~[shareenderchest-1.6.0.jar:?]
	at me.glitch.aitecraft.shareenderchest.ShareEnderChest.onServerStopping(ShareEnderChest.java:90) ~[shareenderchest-1.6.0.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63) ~[fabric-lifecycle-events-v1-2.2.1+5da15ca1f4-ebfc3bde4aae44af.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cpn000$fabric-lifecycle-events-v1$beforeShutdownServer(MinecraftServer.java:10857) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:536) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:707) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by srnyx** [comment]
Experiencing this too, it fixes upon removing Memory Leak Fix

### Versions
Minecraft: 1.19.4
Fabric: 0.14.19
Fastload: [3.3.8](https://modrinth.com/mod/fastload/version/3.3.8)
Memory Leak Fix: [1.0.0 (1.17+)](https://modrinth.com/mod/memoryleakfix/version/v1.0.0)

### Logs
`latest.log`: https://paste.srnyx.xyz/jaciluhawi.yaml
`crash-report`: https://paste.srnyx.xyz/ayequgelop.yaml

**Comment by Talbe1** [comment]
Are there any symptoms due to this error? (yes I'm not the dev but I'm curious)

**Comment by StockiesLad** [comment]
java.lang.NullPointerException: Cannot invoke "me.glitch.aitecraft.shareenderchest.SharedInventory.getList(net.minecraft.class_2371)" because "me.glitch.aitecraft.shareenderchest.ShareEnderChest.sharedInventory" is null

umm, how does fastload even cause this to crash??

**Comment by StockiesLad** [comment]
this is strange, it seems that memleakfix is forceloading mixins. I have no idea what the purpose behind this is but i never coded on the condition that my mixins are directly interfered with.  Can you report this to memleakfix and link this page?

**Comment by StockiesLad** [comment]
fuck. I might've misplaced a mixin

**Comment by StockiesLad** [comment]
nah just checked now not the case

**Comment by StockiesLad** [comment]
aha i might have found the issue. Try this jar ill send you

**Comment by StockiesLad** [comment]
[Fastload+1.18.2-1.20-3.3.8.zip](https://github.com/BumbleSoftware/Fastload/files/11369626/Fastload%2B1.18.2-1.20-3.3.8.zip)
alright I made it into a zip. just unzip and run the mod as normal.

I stopped using mixin for my abstractions and instead converted to dynamic entrypoints. This could potentially resolve the issue.

**Comment by StockiesLad** [comment]
hold on i stuffed something up

**Comment by StockiesLad** [comment]
[Fastload+1.18.2-1.20-3.3.9.zip](https://github.com/BumbleSoftware/Fastload/files/11369842/Fastload%2B1.18.2-1.20-3.3.9.zip)
there we go. try this jar

**Comment by sternschnaube** [comment]
Thank you @StockiesLad, I will test this build later 😊

**Comment by sternschnaube** [comment]
Everything works on client and server - thanks!

**Comment by StockiesLad** [comment]
nice, ill release soon. lemme just keep this open until its released

**Comment by StockiesLad** [comment]
but just close the issue for memory leak fix bc i fixed it on my end and dont want FXMORIN to think he needs to patch a bug,
